import type { Bifrost } from '#bifrost/Bifrost';

export const SETTINGS_KEYS = {
  connectedEngines: 'engine.internal.connectedEngines',
  urlHistory: 'engine.internal.urlHistory',
  infoCache: 'engine.internal.infoCache',
  authTokens: 'engine.internal.authTokens',
  activeEngine: 'engine.internal.activeEngine',
  lastDeployTarget: 'engine.internal.lastDeployTarget',
  dashboardAutoRefresh: 'engine.dashboard.autoRefreshInterval',
  taskInboxAutoRefresh: 'engine.taskInbox.autoRefreshInterval',
  processExplorerAutoRefresh: 'engine.processExplorer.autoRefreshInterval',
  decisionCatalogAutoRefresh: 'engine.decisionCatalog.autoRefreshInterval',
  instanceSearchAutoRefresh: 'engine.instanceSearch.autoRefreshInterval',
  timerSchedulesAutoRefresh: 'engine.timerSchedules.autoRefreshInterval',
  processExplorerPageSize: 'engine.processExplorer.pageSize',
  debuggerDebounce: 'engine.debugger.debounceInterval',
  debuggerAutoFollow: 'engineDebugger.viewer.autoFollow',
  debuggerShowDocumentationMarker: 'engineDebugger.viewer.showDocumentationMarker',
  debuggerShowMultiOutgoingMarkers: 'engineDebugger.viewer.showMultipleOutgoingSequenceFlowsMarkers',
  debuggerDataObjectDetailLevel: 'engineDebugger.viewer.dataObjectDetailLevel',
} as const;

export default function registerSettings(bifrost: Bifrost): void {
  bifrost.settings.register({
    [SETTINGS_KEYS.connectedEngines]: {
      type: 'array',
      default: [],
      label: 'Connected engines',
      description: 'Internal: persisted engine connections.',
      hidden: true,
    },
    [SETTINGS_KEYS.urlHistory]: {
      type: 'array',
      default: [],
      label: 'URL history',
      description: 'Internal: engine URL autocomplete history.',
      hidden: true,
    },
    [SETTINGS_KEYS.infoCache]: {
      type: 'object',
      default: {},
      label: 'Engine info cache',
      description: 'Internal: cached engine information.',
      hidden: true,
    },
    [SETTINGS_KEYS.authTokens]: {
      type: 'object',
      default: {},
      label: 'Auth tokens',
      description: 'Internal: per-engine JWT tokens.',
      hidden: true,
    },
    [SETTINGS_KEYS.activeEngine]: {
      type: 'string',
      default: '',
      label: 'Active engine',
      description: 'Internal: currently selected engine ID.',
      hidden: true,
    },
    [SETTINGS_KEYS.lastDeployTarget]: {
      type: 'string',
      default: '',
      label: 'Last deployment target',
      description: 'Internal: last engine used for deployment.',
      hidden: true,
    },
    [SETTINGS_KEYS.dashboardAutoRefresh]: {
      type: 'string',
      default: '30s',
      label: 'Dashboard auto-refresh interval',
      description: 'Debounce interval for WebSocket-driven dashboard refresh.',
      category: 'Engine',
      enum: ['off', '5s', '10s', '30s', '1min', '5min'],
    },
    [SETTINGS_KEYS.taskInboxAutoRefresh]: {
      type: 'string',
      default: '30s',
      label: 'Task Inbox auto-refresh interval',
      description: 'Debounce interval for WebSocket-driven task inbox refresh.',
      category: 'Engine',
      enum: ['off', '5s', '10s', '30s', '1min', '5min'],
    },
    [SETTINGS_KEYS.processExplorerAutoRefresh]: {
      type: 'string',
      default: '30s',
      label: 'Process Explorer auto-refresh interval',
      description: 'Debounce interval for WebSocket-driven process list refresh.',
      category: 'Engine',
      enum: ['off', '5s', '10s', '30s', '1min', '5min'],
    },
    [SETTINGS_KEYS.decisionCatalogAutoRefresh]: {
      type: 'string',
      default: '30s',
      label: 'Decision Catalog auto-refresh interval',
      description: 'Debounce interval for WebSocket-driven decision catalog refresh.',
      category: 'Engine',
      enum: ['off', '5s', '10s', '30s', '1min', '5min'],
    },
    [SETTINGS_KEYS.instanceSearchAutoRefresh]: {
      type: 'string',
      default: '30s',
      label: 'Instance Search auto-refresh interval',
      description: 'Debounce interval for WebSocket-driven instance search refresh.',
      category: 'Engine',
      enum: ['off', '5s', '10s', '30s', '1min', '5min'],
    },
    [SETTINGS_KEYS.timerSchedulesAutoRefresh]: {
      type: 'string',
      default: '30s',
      label: 'Timer Schedules auto-refresh interval',
      description: 'Debounce interval for WebSocket-driven timer schedules refresh.',
      category: 'Engine',
      enum: ['off', '5s', '10s', '30s', '1min', '5min'],
    },
    [SETTINGS_KEYS.processExplorerPageSize]: {
      type: 'number',
      default: 50,
      label: 'Process Explorer page size',
      description: 'Number of rows per page in the Process Explorer table.',
      category: 'Engine',
      enum: [10, 25, 50, 100],
    },
    [SETTINGS_KEYS.debuggerDebounce]: {
      type: 'number',
      default: 500,
      label: 'Debugger debounce interval',
      description: 'Internal: debounce interval for debugger canvas repaint.',
      hidden: true,
    },
    [SETTINGS_KEYS.debuggerAutoFollow]: {
      type: 'boolean',
      default: false,
      label: 'Auto-follow active flow node',
      description: 'Automatically pan and zoom to the currently active flow node in the debugger.',
      category: 'Engine Debugger',
    },
    [SETTINGS_KEYS.debuggerShowDocumentationMarker]: {
      type: 'boolean',
      default: true,
      label: 'Show documentation markers',
      description: 'Display overlay markers on elements that have documentation attached.',
      category: 'Engine Debugger',
    },
    [SETTINGS_KEYS.debuggerShowMultiOutgoingMarkers]: {
      type: 'boolean',
      default: true,
      label: 'Show multiple outgoing sequence flow markers',
      description: 'Display warning markers on elements with multiple outgoing sequence flows.',
      category: 'Engine Debugger',
    },
    [SETTINGS_KEYS.debuggerDataObjectDetailLevel]: {
      type: 'string',
      default: 'showAll',
      label: 'Data object detail level',
      description: 'Controls visibility of data object associations in the debugger diagram.',
      category: 'Engine Debugger',
      enum: ['showAll', 'hideInputAssociations', 'hideAllAssociations', 'hideAll'],
    },
  });
}
