// window messages
export const IPC_MESSAGE_CLEAR_WINDOW_SOLUTION = 'IPC_MESSAGE_CLEAR_WINDOW_SOLUTION';
export const IPC_MESSAGE_CLOSE_FOCUSED_WINDOW = 'IPC_MESSAGE_CLOSE_FOCUSED_WINDOW';
export const IPC_MESSAGE_HIDE_WINDOW_BY_INSTANCE_ID = 'IPC_MESSAGE_HIDE_WINDOW_BY_INSTANCE_ID';
export const IPC_MESSAGE_CREATE_NEW_WINDOW = 'IPC_MESSAGE_CREATE_NEW_WINDOW';
export const IPC_MESSAGE_EXECUTE_COMMAND_AT_RENDERER = 'IPC_MESSAGE_EXECUTE_COMMAND_AT_RENDERER';
export const IPC_MESSAGE_FOCUS_WINDOW = 'IPC_MESSAGE_FOCUS_WINDOW';
export const IPC_MESSAGE_GET_WINDOWS = 'IPC_MESSAGE_GET_WINDOWS';
export const IPC_MESSAGE_MAXIMIZE_FOCUSED_WINDOW = 'IPC_MESSAGE_MAXIMIZE_FOCUSED_WINDOW';
export const IPC_MESSAGE_MINIMIZE_FOCUSED_WINDOW = 'IPC_MESSAGE_MINIMIZE_FOCUSED_WINDOW';
export const IPC_MESSAGE_QUIT = 'IPC_MESSAGE_QUIT';
export const IPC_MESSAGE_RELOAD_RECENTLY_OPENED = 'IPC_MESSAGE_RELOAD_RECENTLY_OPENED';
export const IPC_MESSAGE_RELOAD_SETTINGS = 'IPC_MESSAGE_RELOAD_SETTINGS';
export const IPC_MESSAGE_RESOLVE_WINDOW_CLOSING_PROMISE_WITH_RESULT =
  'IPC_MESSAGE_RESOLVE_WINDOW_CLOSING_PROMISE_WITH_RESULT';
export const IPC_MESSAGE_SHOW_NATIVE_MESSAGE_BOX = 'IPC_MESSAGE_SHOW_NATIVE_MESSAGE_BOX';
export const IPC_MESSAGE_SHOW_NATIVE_OPEN_DIRECTORY_DIALOG = 'IPC_MESSAGE_SHOW_NATIVE_OPEN_DIRECTORY_DIALOG';
export const IPC_MESSAGE_SHOW_NATIVE_OPEN_FILE_DIALOG = 'IPC_MESSAGE_SHOW_NATIVE_OPEN_FILE_DIALOG';
export const IPC_MESSAGE_SHOW_NATIVE_SAVE_FILE_DIALOG = 'IPC_MESSAGE_SHOW_NATIVE_SAVE_FILE_DIALOG';
export const IPC_MESSAGE_SOLUTION_CHANGED = 'IPC_MESSAGE_SOLUTION_CHANGED';
export const IPC_MESSAGE_TERMINATE = 'IPC_MESSAGE_TERMINATE';
export const IPC_MESSAGE_UPDATE_MAIN_MENU = 'IPC_MESSAGE_UPDATE_MAIN_MENU';
export const IPC_MESSAGE_WARN_ABOUT_UNSAVED_EDITOR_DOCUMENTS_BEFORE_CLOSING =
  'IPC_MESSAGE_WARN_ABOUT_UNSAVED_EDITOR_DOCUMENTS_BEFORE_CLOSING';
export const IPC_MESSAGE_WINDOW_CLOSED_BY_USER = 'IPC_MESSAGE_WINDOW_CLOSED_BY_USER';
export const IPC_MESSAGE_WINDOW_NAVIGATE_TO_URL = 'IPC_MESSAGE_WINDOW_NAVIGATE_TO_URL';
export const IPC_MESSAGE_WINDOW_CLOSED_BY_USER_PROMISE = 'IPC_MESSAGE_WINDOW_CLOSED_BY_USER_PROMISE';

// file operations
export const IPC_INVOKE_SHOW_ITEM_IN_FOLDER = 'IPC_INVOKE_SHOW_ITEM_IN_FOLDER';
export const IPC_INVOKE_OPEN_PATH = 'IPC_INVOKE_OPEN_PATH';
export const IPC_INVOKE_CREATE_DIR = 'IPC_INVOKE_CREATE_DIR';
export const IPC_INVOKE_EXISTS = 'IPC_INVOKE_EXISTS';
export const IPC_INVOKE_GET_APP_PATH = 'IPC_INVOKE_GET_APP_PATH';
export const IPC_INVOKE_GET_SYSTEMINFORMATION = 'IPC_INVOKE_GET_SYSTEMINFORMATION';
export const IPC_INVOKE_IS_DIRECTORY = 'IPC_INVOKE_IS_DIRECTORY';
export const IPC_INVOKE_READ_DIR = 'IPC_INVOKE_READ_DIR';
export const IPC_INVOKE_READ_FILE = 'IPC_INVOKE_READ_FILE';
export const IPC_INVOKE_COPY_FILE_OR_DIRECTORY = 'IPC_INVOKE_COPY_FILE_OR_DIRECTORY';
export const IPC_INVOKE_RENAME_FILE_OR_DIRECTORY = 'IPC_INVOKE_RENAME_FILE_OR_DIRECTORY';
export const IPC_INVOKE_TRASH_ITEM = 'IPC_INVOKE_TRASH_ITEM';
export const IPC_INVOKE_TRAVERSE_DIRECTORY = 'IPC_INVOKE_TRAVERSE_DIRECTORY';
export const IPC_INVOKE_WRITE_FILE = 'IPC_INVOKE_WRITE_FILE';

// updater messages
export const IPC_MESSAGE_ABORT_UPDATE = 'IPC_MESSAGE_ABORT_UPDATE';
export const IPC_MESSAGE_CHECK_FOR_UPDATES = 'IPC_MESSAGE_CHECK_FOR_UPDATES';
export const IPC_MESSAGE_CHECKING_FOR_UPDATES = 'IPC_MESSAGE_CHECKING_FOR_UPDATES';
export const IPC_MESSAGE_DOWNLOAD_UPDATE = 'IPC_MESSAGE_DOWNLOAD_UPDATE';
export const IPC_MESSAGE_QUIT_AND_INSTALL_UPDATE = 'IPC_MESSAGE_QUIT_AND_INSTALL_UPDATE';
export const IPC_MESSAGE_UPDATE_ABORTED = 'IPC_MESSAGE_UPDATE_ABORTED';
export const IPC_MESSAGE_UPDATE_AVAILABLE = 'IPC_MESSAGE_UPDATE_AVAILABLE';
export const IPC_MESSAGE_UPDATE_DOWNLOAD_STARTED = 'IPC_MESSAGE_UPDATE_DOWNLOAD_STARTED';
export const IPC_MESSAGE_UPDATE_DOWNLOADED = 'IPC_MESSAGE_UPDATE_DOWNLOADED';
export const IPC_MESSAGE_UPDATE_ERROR = 'IPC_MESSAGE_UPDATE_ERROR';
export const IPC_MESSAGE_UPDATE_NOT_AVAILABLE = 'IPC_MESSAGE_UPDATE_NOT_AVAILABLE';
export const IPC_MESSAGE_UPDATE_PROGRESS = 'IPC_MESSAGE_UPDATE_PROGRESS';
export const IPC_MESSAGE_UNHANDLED_REJECTION_OR_ERROR = 'IPC_MESSAGE_UNHANDLED_REJECTION_OR_ERROR';

// plugin operations
export const IPC_INVOKE_UNINSTALL_PLUGIN = 'IPC_INVOKE_UNINSTALL_PLUGIN';
export const IPC_MESSAGE_PLUGIN_STATE_CHANGED = 'IPC_MESSAGE_PLUGIN_STATE_CHANGED';

// http
export const IPC_INVOKE_FETCH = 'IPC_INVOKE_FETCH';

// git operations (git-cruiser module)
export {
  IPC_INVOKE_GIT_IS_AVAILABLE,
  IPC_INVOKE_GIT_IS_REPO,
  IPC_INVOKE_GIT_STATUS,
  IPC_INVOKE_GIT_STAGE,
  IPC_INVOKE_GIT_UNSTAGE,
  IPC_INVOKE_GIT_COMMIT,
  IPC_INVOKE_GIT_PUSH,
  IPC_INVOKE_GIT_PULL,
  IPC_INVOKE_GIT_REVERT,
  IPC_INVOKE_GIT_STASH,
  IPC_INVOKE_GIT_STASH_APPLY,
  IPC_INVOKE_GIT_STASH_LIST,
  IPC_INVOKE_GIT_BRANCH_LIST,
  IPC_INVOKE_GIT_BRANCH_SWITCH,
  IPC_INVOKE_GIT_BRANCH_CREATE,
  IPC_INVOKE_GIT_SHOW,
  IPC_INVOKE_GIT_LOG,
} from '#modules/git-cruiser/GitIpcChannels';
