export type MenuBarItemArea = 'left' | 'center' | 'right';

/**
 * MenuBarItems are POJOs, generated by MenuBarItem factory functions registered via `MenuBarMediator`.
 */
export type MenuBarItemFactoryFn = (...factoryFnArgs: any[]) => MenuBarItem[];

/**
 * MenuBarItems are POJOs, generated by MenuBarItem factory functions registered via `MenuBarMediator`,
 * which can be modified by modifier functions (which are registrered via the mediator as well).
 */
export type MenuBarItemModifierFn = (menuBarItemMap: MenuBarItemMap, ...factoryFnArgs: any[]) => MenuBarItemMap;

export type MenuBarItemMap = {
  readonly left: MenuBarItem[];
  readonly center: MenuBarItem[];
  readonly right: MenuBarItem[];
};

export type MenuBarItem =
  | MenuBarItem_Button
  | MenuBarItem_Divider
  | MenuBarItem_Icon
  | MenuBarItem_Menu
  | MenuBarItem_PaneContentToggle
  | MenuBarItem_Select
  | MenuBarItem_Text;

export type MenuBarItem_Button = {
  type: 'button';

  readonly id?: string;

  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;

  /**
   * The icon id for the icon shown in the left menubar
   */
  readonly icon: string;

  /**
   * Name of the command to execute on click
   */
  readonly command: string;

  /**
   * Optional: Arguments for the command
   */
  readonly commandArgs?: any[];

  /**
   * Text to display as tooltip
   */
  readonly tooltip: string;
};

export type MenuBarItem_Divider = {
  type: 'divider';

  readonly id?: string;

  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;
};

export type MenuBarItem_Icon = {
  type: 'icon';

  readonly id?: string;

  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;

  /**
   * Text to display as tooltip
   */
  readonly tooltip: string;

  /**
   * The icon id for the icon shown in the left menubar
   */
  readonly icon: string;
};

export type MenuBarItem_Menu = {
  type: 'menu';

  readonly id?: string;

  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;

  /**
   * The icon id for the icon shown in the left menubar
   */
  readonly icon: string;

  /**
   * The ID of the menu to display on click
   */
  readonly menu: string;

  /**
   * Text to display as tooltip
   */
  readonly tooltip?: string;
};

/**
 * A `PaneContentToggle` renders as a button that controls which content is displayed in a pane area.
 * Clicking it selects the associated pane; the component determines its own `active` state at render time.
 */
export type MenuBarItem_PaneContentToggle = {
  type: 'pane_content_toggle';

  readonly id?: string;

  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;

  /**
   * The icon id for the icon shown in the menu bar
   */
  readonly icon: string;

  /**
   * Text to display as tooltip
   */
  readonly tooltip: string;

  /**
   * The pane area this toggle controls (e.g. 'left', 'right', 'bottom')
   */
  readonly paneAreaId: 'left' | 'right' | 'bottom';

  /**
   * The pane ID to select when clicked (e.g. 'pane/left/explorer')
   */
  readonly paneId: string;
};

export type MenuBarItem_Select = {
  type: 'select';

  readonly id?: string;

  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;

  /**
   * The selected value
   */
  readonly value?: any;

  /**
   * A list of entries consisting of `value` and `label`
   */
  readonly entries: MenuBarItem_SelectEntry[];

  /**
   * Name of the command to execute on click
   */
  readonly command: string;

  /**
   * Optional: Arguments for the command
   */
  readonly commandArgs?: any[];

  /**
   * Text to display as tooltip
   */
  readonly tooltip?: string;
};

export type MenuBarItem_Text = {
  type: 'text';

  readonly id?: string;

  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;

  /**
   * Text to display as tooltip
   */
  readonly tooltip?: string;

  /**
   * Text to be displayed
   */
  readonly label: string;
};

export type MenuBarItem_SelectEntry = {
  readonly value: any;
  readonly label: string;
};

export type MenuBarViewData = {
  readonly visible: boolean;
  readonly items: MenuBarItemMap;
};

// the serialized data that goes into storage is the same as the data handed to the view (for now)
// but these are two conceptually different things, which is why we alias them here
export type MenuBarSerialized = MenuBarViewData;
