/**
 * `header` sits right of the workbench header's categories. `pageBar` is right-pinned in the page bar;
 * it is internal: plugins only get `header`.
 */
export type MenuBarItemArea = 'header' | 'pageBar';

/**
 * MenuBarItems are POJOs, generated by MenuBarItem factory functions registered via `MenuBarMediator`.
 */
export type MenuBarItemFactoryFn = (...factoryFnArgs: any[]) => MenuBarItem[];

/**
 * MenuBarItems are POJOs, generated by MenuBarItem factory functions registered via `MenuBarMediator`,
 * which can be modified by modifier functions (which are registrered via the mediator as well).
 */
export type MenuBarItemModifierFn = (menuBarItemMap: MenuBarItemMap, ...factoryFnArgs: any[]) => MenuBarItemMap;

export type MenuBarItemMap = {
  readonly header: MenuBarItem[];
  readonly pageBar: MenuBarItem[];
};

/** Items may be limited to workbench pages; items without `pages` show on every page. */
export type MenuBarItem = MenuBarItemVariant & { readonly pages?: string[] };

type MenuBarItemVariant =
  | MenuBarItem_Button
  | MenuBarItem_Divider
  | MenuBarItem_Icon
  | MenuBarItem_Menu
  | MenuBarItem_Select
  | MenuBarItem_Text;

export type MenuBarItem_Button = {
  type: 'button';

  readonly id?: string;

  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;

  /**
   * The icon id for the icon shown in the left menubar
   */
  readonly icon: string;

  /**
   * Name of the command to execute on click
   */
  readonly command: string;

  /**
   * Optional: Arguments for the command
   */
  readonly commandArgs?: any[];

  /**
   * Text to display as tooltip
   */
  readonly tooltip: string;
};

export type MenuBarItem_Divider = {
  type: 'divider';

  readonly id?: string;

  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;
};

export type MenuBarItem_Icon = {
  type: 'icon';

  readonly id?: string;

  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;

  /**
   * Text to display as tooltip
   */
  readonly tooltip: string;

  /**
   * The icon id for the icon shown in the left menubar
   */
  readonly icon: string;
};

export type MenuBarItem_Menu = {
  type: 'menu';

  readonly id?: string;

  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;

  /**
   * The icon id for the icon shown in the left menubar
   */
  readonly icon: string;

  /**
   * The ID of the menu to display on click
   */
  readonly menu: string;

  /**
   * Text to display as tooltip
   */
  readonly tooltip?: string;
};

export type MenuBarItem_Select = {
  type: 'select';

  readonly id?: string;

  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;

  /**
   * The selected value
   */
  readonly value?: any;

  /**
   * A list of entries consisting of `value` and `label`
   */
  readonly entries: MenuBarItem_SelectEntry[];

  /**
   * Name of the command to execute on click
   */
  readonly command: string;

  /**
   * Optional: Arguments for the command
   */
  readonly commandArgs?: any[];

  /**
   * Text to display as tooltip
   */
  readonly tooltip?: string;
};

export type MenuBarItem_Text = {
  type: 'text';

  readonly id?: string;

  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;

  /**
   * Text to display as tooltip
   */
  readonly tooltip?: string;

  /**
   * Text to be displayed
   */
  readonly label: string;
};

export type MenuBarItem_SelectEntry = {
  readonly value: any;
  readonly label: string;
};

export type MenuBarViewData = {
  readonly visible: boolean;
  readonly items: MenuBarItemMap;
};

// the serialized data that goes into storage is the same as the data handed to the view (for now)
// but these are two conceptually different things, which is why we alias them here
export type MenuBarSerialized = MenuBarViewData;
