export type StatusBarItemArea = 'left' | 'center' | 'right';

/**
 * StatusBarItems are POJOs, generated by StatusBarItem factory functions registered via `StatusBarMediator`.
 */
export type StatusBarItemFactoryFn = (...factoryFnArgs: any[]) => StatusBarItem[];

export type StatusBarItem = StatusBarItem_Button | StatusBarItem_Divider | StatusBarItem_Menu;

export type StatusBarContent = StatusBarContentObject | StatusBarContentObject[];

type StatusBarContentObject = StatusBarContent_Text | StatusBarContent_Icon;

type StatusBarContent_Icon = {
  type: 'icon';

  /**
   * the icon id for the icon shown in the status bar
   */
  readonly icon: string;
};

type StatusBarContent_Text = {
  type: 'text';

  /**
   * Text to be displayed
   */
  readonly label: string;
};

/**
 * A `StatusBarItemObject_Button` represents an icon in the StatusBar which acts as a button and
 * triggers a pre-defined command upon click.
 **/
export type StatusBarItem_Button = {
  type: 'button';

  /**
   * A unique id
   */
  readonly id: string;

  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;

  /**
   * Text to display as tooltip
   */
  readonly tooltip?: string;

  readonly content: StatusBarContent;

  /**
   * Name of the command to execute on click
   */
  readonly command: string;

  /**
   * Optional: Arguments for the command
   */
  readonly commandArgs?: any[];

  /**
   * The ID of the menu to display on right-click
   */
  readonly contextMenuId?: string;

  /**
   * Optional: Arguments for the context menu
   */
  readonly contextMenuArgs?: any[];

  /**
   * whether or the status is currently actively displayed
   */
  readonly active?: boolean;
};

/**
 * A `StatusBarItemObject_Divider` represents a separating divider for icons in the StatusBar.
 **/
export type StatusBarItem_Divider = {
  type: 'divider';

  /**
   * A unique id
   */
  readonly id: string;

  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;
};

/**
 * A `StatusBarItemObject_Menu` represents an icon in the StatusBar which acts as a menu trigger,
 * triggering a pre-defined menu upon click.
 **/
export type StatusBarItem_Menu = {
  type: 'menu';

  /**
   * A unique id
   */
  readonly id: string;

  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;

  /**
   * Text to display as tooltip
   */
  readonly tooltip?: string;

  readonly content: StatusBarContent;

  /**
   * The ID of the menu to display on click
   */
  readonly menu: string;

  /**
   * Optional: Set to `true` when the item is currently actively displayed.
   */
  // TODO: is this used?
  readonly active?: boolean;
};

export type ProgressHandle = {
  update(label: string): void;
  done(): void;
};

export type StatusBarViewData = {
  readonly visible: boolean;
  readonly items: {
    readonly left: StatusBarItem[];
    readonly center: StatusBarItem[];
    readonly right: StatusBarItem[];
  };
  readonly progressLabel: string | null;
};

// the serialized data that goes into storage is the same as the data handed to the view (for now)
// but these are two conceptually different things, which is why we alias them here
export type StatusBarSerialized = StatusBarViewData;
