import type { Bifrost } from '#bifrost/Bifrost';

export function initializePanes(bifrost: Bifrost): void {
  registerDmnTracePanes(bifrost);
  bifrost.panes.prependToPaneGroup('right', 'property', [
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/MultipleSelections',
      'EngineDebugger/pane-providers/MultipleSelections',
      require('../property-panel/MultipleSelectionsPane'),
    ),
  ]);

  bifrost.panes.prependToPaneGroup('right', 'property', [
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/GenericProperties',
      'EngineDebugger/pane-providers/GenericProperties',
      require('../property-panel/GenericPropertyPane'),
    ),
  ]);

  registerProcessInstancePanes(bifrost);
  registerAssociationPanes(bifrost);
  registerFlowNodeInstancePanes(bifrost);
  registerDataObjectPanes(bifrost);
}

function registerProcessInstancePanes(bifrost: Bifrost): void {
  bifrost.panes.prependToPaneGroup('right', 'property', [
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/ProcessModelInfo',
      'EngineDebugger/pane-providers/ProcessModelInfo',
      require('../property-panel/ProcessInstance/ProcessModelInfoPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/ProcessDefinitionInfo',
      'EngineDebugger/pane-providers/ProcessDefinitionInfo',
      require('../property-panel/ProcessInstance/ProcessDefinitionInfoPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/CollapsedPool',
      'EngineDebugger/pane-providers/CollapsedPool',
      require('../property-panel/ProcessInstance/CollapsedPoolPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/ProcessInstanceError',
      'EngineDebugger/pane-providers/ProcessInstanceError',
      require('../property-panel/ProcessInstance/ProcessInstanceErrorPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/ProcessInstanceRuntime',
      'EngineDebugger/pane-providers/ProcessInstanceRuntime',
      require('../property-panel/ProcessInstance/ProcessInstanceRuntimePane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/ProcessInstanceUser',
      'EngineDebugger/pane-providers/ProcessInstanceUser',
      require('../property-panel/ProcessInstance/ProcessInstanceUserPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/ContextVariables',
      'EngineDebugger/pane-providers/ContextVariables',
      require('../property-panel/ProcessInstance/ContextVariablesPane'),
    ),
  ]);

  bifrost.panes.prependToPaneGroup('right', 'dataflow', [
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/ProcessInstanceTriggeredBy',
      'EngineDebugger/pane-providers/ProcessInstanceTriggeredBy',
      require('../property-panel/ProcessInstance/ProcessInstanceTriggeredByPane'),
    ),
  ]);
}

function registerAssociationPanes(bifrost: Bifrost): void {
  bifrost.panes.prependToPaneGroup('right', 'property', [
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/SequenceFlow',
      'EngineDebugger/pane-providers/SequenceFlow',
      require('../property-panel/Associations/SequenceFlowPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/DataInputAssociation',
      'EngineDebugger/pane-providers/DataInputAssociation',
      require('../property-panel/Associations/DataInputAssociationPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/DataOutputAssociation',
      'EngineDebugger/pane-providers/DataOutputAssociation',
      require('../property-panel/Associations/DataOutputAssociationPane'),
    ),
  ]);
}

function registerFlowNodeInstancePanes(bifrost: Bifrost): void {
  bifrost.panes.prependToPaneGroup('right', 'dataflow', [
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/NextFlowNodeInstances',
      'EngineDebugger/pane-providers/NextFlowNodeInstances',
      require('../property-panel/FlowNode/NextFlowNodeInstancesPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/PreviousFlowNodeInstances',
      'EngineDebugger/pane-providers/PreviousFlowNodeInstances',
      require('../property-panel/FlowNode/PreviousFlowNodeInstancesPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/EventTriggerSource',
      'EngineDebugger/pane-providers/EventTriggerSource',
      require('../property-panel/FlowNode/EventTriggerSourcePane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/TriggeredProcessInstances',
      'EngineDebugger/pane-providers/TriggeredProcessInstances',
      require('../property-panel/FlowNode/TriggeredProcessInstancesPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/ContinuedEvents',
      'EngineDebugger/pane-providers/ContinuedEvents',
      require('../property-panel/FlowNode/ContinuedEventsPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/CallActivityChildProcessInstance',
      'EngineDebugger/pane-providers/CallActivityChildProcessInstance',
      require('../property-panel/FlowNode/CallActivityChildProcessInstancePane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/SubProcessChildProcessInstance',
      'EngineDebugger/pane-providers/SubProcessChildProcessInstance',
      require('../property-panel/FlowNode/SubProcessChildProcessInstancePane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/WrittenDataObjectValues',
      'EngineDebugger/pane-providers/WrittenDataObjectValues',
      require('../property-panel/FlowNode/WrittenDataObjectValuesPane'),
    ),
  ]);

  bifrost.panes.prependToPaneGroup('right', 'scripting', [
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/InputMappings',
      'EngineDebugger/pane-providers/InputMappings',
      require('../property-panel/FlowNode/InputMappingsPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/OutputMappings',
      'EngineDebugger/pane-providers/OutputMappings',
      require('../property-panel/FlowNode/OutputMappingsPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/PayloadContract',
      'EngineDebugger/pane-providers/PayloadContract',
      require('../property-panel/FlowNode/PayloadContractPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/ResultContract',
      'EngineDebugger/pane-providers/ResultContract',
      require('../property-panel/FlowNode/ResultContractPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/CallActivityPayload',
      'EngineDebugger/pane-providers/CallActivityPayload',
      require('../property-panel/FlowNode/CallActivityPayloadPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/HttpServiceTaskMethod',
      'EngineDebugger/pane-providers/HttpServiceTaskMethod',
      require('../property-panel/FlowNode/HttpServiceTaskMethodPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/HttpServiceTaskUrl',
      'EngineDebugger/pane-providers/HttpServiceTaskUrl',
      require('../property-panel/FlowNode/HttpServiceTaskUrlPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/HttpServiceTaskAuthorization',
      'EngineDebugger/pane-providers/HttpServiceTaskAuthorization',
      require('../property-panel/FlowNode/HttpServiceTaskAuthorizationPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/HttpServiceTaskContentType',
      'EngineDebugger/pane-providers/HttpServiceTaskContentType',
      require('../property-panel/FlowNode/HttpServiceTaskContentTypePane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/HttpServiceTaskBody',
      'EngineDebugger/pane-providers/HttpServiceTaskBody',
      require('../property-panel/FlowNode/HttpServiceTaskBodyPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/BusinessRuleTaskPayload',
      'EngineDebugger/pane-providers/BusinessRuleTaskPayload',
      require('../property-panel/FlowNode/BusinessRuleTaskPayloadPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/SendTaskPayload',
      'EngineDebugger/pane-providers/SendTaskPayload',
      require('../property-panel/FlowNode/SendTaskPayloadPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/MessageEventPayload',
      'EngineDebugger/pane-providers/MessageEventPayload',
      require('../property-panel/FlowNode/MessageEventPayloadPane'),
    ),
  ]);

  bifrost.panes.prependToPaneGroup('right', 'documentation', [
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/Documentation',
      'EngineDebugger/pane-providers/Documentation',
      require('../property-panel/DocumentationPane'),
    ),
  ]);

  bifrost.panes.prependToPaneGroup('right', 'property', [
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/FlowNodeInstance',
      'EngineDebugger/pane-providers/FlowNodeInstance',
      require('../property-panel/FlowNode/FlowNodeInstancePane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/FlowNodeInfo',
      'EngineDebugger/pane-providers/FlowNodeInfo',
      require('../property-panel/FlowNode/FlowNodeInfoPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/InputToken',
      'EngineDebugger/pane-providers/InputToken',
      require('../property-panel/FlowNode/InputTokenPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/OutputToken',
      'EngineDebugger/pane-providers/OutputToken',
      require('../property-panel/FlowNode/OutputTokenPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/LoopConfiguration',
      'EngineDebugger/pane-providers/LoopConfiguration',
      require('../property-panel/FlowNode/LoopConfigurationPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/SequentialMultiInstance',
      'EngineDebugger/pane-providers/SequentialMultiInstance',
      require('../property-panel/FlowNode/SequentialMultiInstancePane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/FlowNodeInstanceError',
      'EngineDebugger/pane-providers/FlowNodeInstanceError',
      require('../property-panel/FlowNode/FlowNodeInstanceErrorPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/CallActivityDefinition',
      'EngineDebugger/pane-providers/CallActivityDefinition',
      require('../property-panel/FlowNode/CallActivityDefinitionPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/ExclusiveSplitGateway',
      'EngineDebugger/pane-providers/ExclusiveSplitGateway',
      require('../property-panel/FlowNode/ExclusiveSplitGatewayPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/BusinessRuleTaskInstance',
      'EngineDebugger/pane-providers/BusinessRuleTaskInstance',
      require('../property-panel/FlowNode/BusinessRuleTaskInstancePane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/BusinessRuleTaskTopic',
      'EngineDebugger/pane-providers/BusinessRuleTaskTopic',
      require('../property-panel/FlowNode/BusinessRuleTaskTopicPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/ReceiveTask',
      'EngineDebugger/pane-providers/ReceiveTask',
      require('../property-panel/FlowNode/ReceiveTaskPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/SendTask',
      'EngineDebugger/pane-providers/SendTask',
      require('../property-panel/FlowNode/SendTaskPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/ConditionalEventDefinition',
      'EngineDebugger/pane-providers/ConditionalEventDefinition',
      require('../property-panel/FlowNode/ConditionalEventDefinitionPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/ErrorBoundaryEventDefinition',
      'EngineDebugger/pane-providers/ErrorBoundaryEventDefinition',
      require('../property-panel/FlowNode/ErrorBoundaryEventDefinitionPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/ErrorEndEventDefinition',
      'EngineDebugger/pane-providers/ErrorEndEventDefinition',
      require('../property-panel/FlowNode/ErrorEndEventDefinitionPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/LinkCatchEventDefinition',
      'EngineDebugger/pane-providers/LinkCatchEventDefinition',
      require('../property-panel/FlowNode/LinkCatchEventDefinitionPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/LinkThrowEventDefinition',
      'EngineDebugger/pane-providers/LinkThrowEventDefinition',
      require('../property-panel/FlowNode/LinkThrowEventDefinitionPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/MessageEventName',
      'EngineDebugger/pane-providers/MessageEventName',
      require('../property-panel/FlowNode/MessageEventNamePane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/SignalEventName',
      'EngineDebugger/pane-providers/SignalEventName',
      require('../property-panel/FlowNode/SignalEventNamePane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/EscalationThrowEvent',
      'EngineDebugger/pane-providers/EscalationThrowEvent',
      require('../property-panel/FlowNode/EscalationThrowEventPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/EscalationBoundaryEvent',
      'EngineDebugger/pane-providers/EscalationBoundaryEvent',
      require('../property-panel/FlowNode/EscalationBoundaryEventPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/TimerEventDefinition',
      'EngineDebugger/pane-providers/TimerEventDefinition',
      require('../property-panel/FlowNode/TimerEventDefinitionPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/UserTaskFormFields',
      'EngineDebugger/pane-providers/UserTaskFormFields',
      require('../property-panel/FlowNode/UserTaskFormFieldsPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/UserTaskAssignedUsers',
      'EngineDebugger/pane-providers/UserTaskAssignedUsers',
      require('../property-panel/FlowNode/UserTaskAssignedUsersPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/ManualTask',
      'EngineDebugger/pane-providers/ManualTask',
      require('../property-panel/FlowNode/ManualTaskPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/UntypedTask',
      'EngineDebugger/pane-providers/UntypedTask',
      require('../property-panel/FlowNode/UntypedTaskPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/ScriptTask',
      'EngineDebugger/pane-providers/ScriptTask',
      require('../property-panel/FlowNode/ScriptTaskPane'),
    ),
  ]);
}

function registerDmnTracePanes(bifrost: Bifrost): void {
  bifrost.panes.prependToPaneGroup('right', 'property', [
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/DmnTraceOverview',
      'EngineDebugger/pane-providers/DmnTraceOverview',
      require('../dmn-trace/panes/TraceOverviewPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/DmnDecisionTraceDetail',
      'EngineDebugger/pane-providers/DmnDecisionTraceDetail',
      require('../dmn-trace/panes/DecisionTraceDetailPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/DmnBkmTrace',
      'EngineDebugger/pane-providers/DmnBkmTrace',
      require('../dmn-trace/panes/BkmTracePane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/DmnCoercionTrace',
      'EngineDebugger/pane-providers/DmnCoercionTrace',
      require('../dmn-trace/panes/CoercionTracePane'),
    ),
  ]);
}

function registerDataObjectPanes(bifrost: Bifrost): void {
  bifrost.panes.prependToPaneGroup('right', 'property', [
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/DataObject',
      'EngineDebugger/pane-providers/DataObject',
      require('../property-panel/DataObject/DataObjectPane'),
    ),
    bifrost.panes.getPaneViaPaneProvider(
      'EngineDebugger/panes/DataObjectValues',
      'EngineDebugger/pane-providers/DataObjectValues',
      require('../property-panel/DataObject/DataObjectValuesPane'),
    ),
  ]);
}
