export declare type MenuBarItemArea = 'left' | 'center' | 'right';
/**
 * MenuBarItems are POJOs, generated by MenuBarItem factory functions registered via `MenuBarMediator`.
 */
export declare type MenuBarItemFactoryFn = (...factoryFnArgs: any[]) => MenuBarItem[];
/**
 * MenuBarItems are POJOs, generated by MenuBarItem factory functions registered via `MenuBarMediator`,
 * which can be modified by modifier functions (which are registrered via the mediator as well).
 */
export declare type MenuBarItemModifierFn = (menuBarItemMap: MenuBarItemMap, ...factoryFnArgs: any[]) => MenuBarItemMap;
export declare type MenuBarItemMap = {
  readonly left: MenuBarItem[];
  readonly center: MenuBarItem[];
  readonly right: MenuBarItem[];
};
export declare type MenuBarItem =
  | MenuBarItem_Button
  | MenuBarItem_Divider
  | MenuBarItem_Icon
  | MenuBarItem_Menu
  | MenuBarItem_PaneContentToggle
  | MenuBarItem_Select
  | MenuBarItem_Text;
export declare type MenuBarItem_Button = {
  type: 'button';
  readonly id?: string;
  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;
  /**
   * The icon id for the icon shown in the menu bar
   */
  readonly icon: string;
  /**
   * Name of the command to execute on click
   */
  readonly command: string;
  /**
   * Optional: Arguments for the command
   */
  readonly commandArgs?: any[];
  /**
   * Text to display as tooltip
   */
  readonly tooltip: string;
};
export declare type MenuBarItem_Divider = {
  type: 'divider';
  readonly id?: string;
  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;
};
export declare type MenuBarItem_Icon = {
  type: 'icon';
  readonly id?: string;
  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;
  /**
   * Text to display as tooltip
   */
  readonly tooltip: string;
  /**
   * The icon id for the icon shown in the menu bar
   */
  readonly icon: string;
};
export declare type MenuBarItem_Menu = {
  type: 'menu';
  readonly id?: string;
  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;
  /**
   * The icon id for the icon shown in the menu bar
   */
  readonly icon: string;
  /**
   * The ID of the menu to display on click
   */
  readonly menu: string;
  /**
   * Text to display as tooltip
   */
  readonly tooltip?: string;
};
export declare type MenuBarItem_PaneContentToggle = {
  type: 'pane_content_toggle';
  readonly id?: string;
  readonly visible?: boolean;
  readonly icon: string;
  readonly tooltip: string;
  readonly paneAreaId: 'left' | 'right' | 'bottom';
  readonly paneId: string;
};
export declare type MenuBarItem_Select = {
  type: 'select';
  readonly id?: string;
  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;
  /**
   * The selected value
   */
  readonly value?: any;
  /**
   * A list of entries consisting of `value` and `label`
   */
  readonly entries: MenuBarItem_SelectEntry[];
  /**
   * Name of the command to execute on click
   */
  readonly command: string;
  /**
   * Optional: Arguments for the command
   */
  readonly commandArgs?: any[];
  /**
   * Text to display as tooltip
   */
  readonly tooltip?: string;
};
export declare type MenuBarItem_Text = {
  type: 'text';
  readonly id?: string;
  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;
  /**
   * Text to display as tooltip
   */
  readonly tooltip?: string;
  /**
   * Text to be displayed
   */
  readonly label: string;
};
export declare type MenuBarItem_SelectEntry = {
  readonly value: any;
  readonly label: string;
};
export declare type MenuBarViewData = {
  readonly visible: boolean;
  readonly items: MenuBarItemMap;
};
export declare type MenuBarSerialized = MenuBarViewData;
