export declare type StatusBarItemArea = 'left' | 'center' | 'right';
/**
 * StatusBarItems are POJOs, generated by StatusBarItem factory functions registered via `StatusBarMediator`.
 */
export declare type StatusBarItemFactoryFn = (...factoryFnArgs: any[]) => StatusBarItem[];
export declare type StatusBarItem = StatusBarItem_Button | StatusBarItem_Divider | StatusBarItem_Menu;
export declare type StatusBarContent = StatusBarContentObject | StatusBarContentObject[];
declare type StatusBarContentObject = StatusBarContent_Text | StatusBarContent_Icon;
declare type StatusBarContent_Icon = {
  type: 'icon';
  /**
   * the icon id for the icon shown in the status bar
   */
  readonly icon: string;
};
declare type StatusBarContent_Text = {
  type: 'text';
  /**
   * Text to be displayed
   */
  readonly label: string;
};
/**
 * A `StatusBarItemObject_Button` represents an icon in the StatusBar which acts as a button and
 * triggers a pre-defined command upon click.
 **/
export declare type StatusBarItem_Button = {
  type: 'button';
  /**
   * A unique id
   */
  readonly id: string;
  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;
  /**
   * Text to display as tooltip
   */
  readonly tooltip?: string;
  readonly content: StatusBarContent;
  /**
   * Name of the command to execute on click
   */
  readonly command: string;
  /**
   * Optional: Arguments for the command
   */
  readonly commandArgs?: any[];
  /**
   * The ID of the menu to display on right-click
   */
  readonly contextMenuId?: string;

  /**
   * Optional: Arguments for the context menu
   */
  readonly contextMenuArgs?: any[];

  /**
   * whether or the status is currently actively displayed
   */
  readonly active?: boolean;
};
/**
 * A `StatusBarItemObject_Divider` represents a separating divider for icons in the StatusBar.
 **/
export declare type StatusBarItem_Divider = {
  type: 'divider';
  /**
   * A unique id
   */
  readonly id: string;
  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;
};
/**
 * A `StatusBarItemObject_Menu` represents an icon in the StatusBar which acts as a menu trigger,
 * triggering a pre-defined menu upon click.
 **/
export declare type StatusBarItem_Menu = {
  type: 'menu';
  /**
   * A unique id
   */
  readonly id: string;
  /**
   * Defaults to "true".
   */
  readonly visible?: boolean;
  /**
   * Text to display as tooltip
   */
  readonly tooltip?: string;
  readonly content: StatusBarContent;
  /**
   * The ID of the menu to display on click
   */
  readonly menu: string;
  /**
   * Optional: Set to `true` when the item is currently actively displayed.
   */
  readonly active?: boolean;
};
export declare type ProgressHandle = {
  update(label: string): void;
  done(): void;
};

export declare type StatusBarViewData = {
  readonly visible: boolean;
  readonly items: {
    readonly left: StatusBarItem[];
    readonly center: StatusBarItem[];
    readonly right: StatusBarItem[];
  };
  readonly progressLabel: string | null;
};
export declare type StatusBarSerialized = StatusBarViewData;
export {};
