export const EVENT_EDITOR_DOCUMENT_DATA_UPDATED = 'EVENT_EDITOR_DOCUMENT_DATA_UPDATED';
export const EVENT_EDITOR_DOCUMENT_METADATA_UPDATED = 'EVENT_EDITOR_DOCUMENT_METADATA_UPDATED';
export const EVENT_EDITOR_DOCUMENT_TITLE_UPDATED = 'EVENT_EDITOR_DOCUMENT_TITLE_UPDATED';
export const EVENT_EDITOR_DOCUMENT_URI_UPDATED = 'EVENT_EDITOR_DOCUMENT_URI_UPDATED';
export const EVENT_EDITOR_DOCUMENT_LABEL_UPDATED = 'EVENT_EDITOR_DOCUMENT_LABEL_UPDATED';
export const EVENT_EDITOR_DOCUMENT_FRAGMENT_ID_UPDATED = 'EVENT_EDITOR_DOCUMENT_FRAGMENT_ID_UPDATED';

export const EVENT_EDITOR_AREA_LAYOUT_UPDATED = 'EVENT_EDITOR_AREA_LAYOUT_UPDATED';
export const EVENT_EDITOR_AREA_FOCUS_UPDATED = 'EVENT_EDITOR_AREA_FOCUS_UPDATED';
export const EVENT_EDITOR_AREA_DOCUMENT_CLOSED = 'EVENT_EDITOR_AREA_DOCUMENT_CLOSED';

// TODO: which of these are "internal" to the *Managers they originate from?
export const EVENT_DATA_UPDATED = 'EVENT_DATA_UPDATED';
export const EVENT_METADATA_UPDATED = 'EVENT_METADATA_UPDATED';
export const EVENT_URI_CHANGED = 'EVENT_URI_CHANGED';
export const EVENT_LABEL_CHANGED = 'EVENT_LABEL_CHANGED';
export const EVENT_FRAGMENT_ID_UPDATED = 'EVENT_FRAGMENT_ID_UPDATED';
