export const EVENT_SETTINGS_CHANGED = 'EVENT_SETTINGS_CHANGED';
export const EVENT_SETTINGS_MERGED = 'EVENT_SETTINGS_MERGED';
export const EVENT_SETTINGS_SCHEMA_REGISTERED = 'EVENT_SETTINGS_SCHEMA_REGISTERED';
