import { syntaxHighlighting } from '@codemirror/language';
import { EditorView } from '@codemirror/view';
import { classHighlighter } from '@lezer/highlight';

/**
 * CodeMirror 6 theme extension that references the Studio's CSS custom
 * properties (`--theme-feel-*`). Theme switching happens at the CSS level
 * via the `.bifrost-theme--light` / `--dark` class swap — no JS
 * reconfiguration is needed.
 *
 * `EditorView.theme()` takes precedence over the feel-editor's built-in
 * `EditorView.baseTheme()`, so our overrides win naturally.
 *
 * The `tok-*` selectors target stable class names added by
 * `classHighlighter` from `@lezer/highlight`. These override the
 * feel-editor's bundled `feelLight` HighlightStyle (from `@bpmn-io/cm-theme`)
 * which hardcodes dark text colors (e.g. `#24292f` for property names)
 * that are invisible on dark backgrounds. Because `EditorView.theme()`
 * scopes its rules to `.cm-editor.ͼXX`, our selectors have higher
 * specificity than HighlightStyle's flat `.ͼYY` selectors.
 */
export const studioFeelTheme = EditorView.theme({
  '&': {
    backgroundColor: 'var(--theme-feel-bg)',
    color: 'var(--theme-feel-fg)',
  },
  '.cm-content': {
    caretColor: 'var(--theme-feel-cursor)',
  },
  '.cm-cursor': {
    borderLeftColor: 'var(--theme-feel-cursor)',
  },
  '&.cm-focused .cm-selectionBackground, .cm-selectionBackground': {
    backgroundColor: 'var(--theme-feel-selection-bg)',
  },
  '.cm-activeLine': {
    backgroundColor: 'var(--theme-feel-active-line-bg)',
  },
  '.cm-gutters': {
    backgroundColor: 'var(--theme-feel-gutter-bg)',
    borderRight: '1px solid var(--theme-feel-border)',
  },
  // Legacy class-name-based highlighting (from @bpmn-io/lang-feel decorations)
  '& .variableName': { color: 'var(--theme-feel-variable)' },
  '& .number': { color: 'var(--theme-feel-number)' },
  '& .string': { color: 'var(--theme-feel-string)' },
  '& .bool': { color: 'var(--theme-feel-bool)' },
  '& .function': { color: 'var(--theme-feel-function)' },
  '& .control': { color: 'var(--theme-feel-keyword)' },
  // Lezer tag-based highlighting via classHighlighter (tok-* classes).
  // These override feelLight's HighlightStyle due to higher specificity.
  '& .tok-keyword': { color: 'var(--theme-feel-keyword)' },
  '& .tok-bool': { color: 'var(--theme-feel-bool)' },
  '& .tok-null': { color: 'var(--theme-feel-keyword)' },
  '& .tok-propertyName': { color: 'var(--theme-feel-fg)' },
  '& .tok-definition': { color: 'var(--theme-feel-fg)' },
  '& .tok-variableName': { color: 'var(--theme-feel-variable)' },
  '& .tok-string': { color: 'var(--theme-feel-string)' },
  '& .tok-string2': { color: 'var(--theme-feel-string)' },
  '& .tok-number': { color: 'var(--theme-feel-number)' },
  '& .tok-comment': { color: 'var(--theme-feel-comment)' },
  '& .tok-operator': { color: 'var(--theme-feel-fg)' },
  '& .tok-punctuation': { color: 'var(--theme-feel-fg)' },
  // Tooltips
  '.cm-tooltip': {
    backgroundColor: 'var(--theme-feel-tooltip-bg)',
    color: 'var(--theme-feel-tooltip-fg)',
    border: '1px solid var(--theme-feel-tooltip-border)',
  },
  '.cm-tooltip-autocomplete ul li[aria-selected]': {
    backgroundColor: 'var(--theme-feel-tooltip-selected-bg)',
    color: 'var(--theme-feel-tooltip-selected-fg)',
  },
});

/**
 * Adds stable `tok-*` class names to syntax-highlighted spans via the
 * Lezer `classHighlighter`. These classes are targeted by selectors in
 * `studioFeelTheme` above. This is more reliable than a competing
 * `HighlightStyle` because `EditorView.theme()` scoped selectors always
 * beat the flat class selectors generated by `HighlightStyle.define()`.
 */
export const studioFeelHighlighting = syntaxHighlighting(classHighlighter);
